(() => {
  const basic = [
    ["기준금리란?","중앙은행이 물가와 금융안정을 위해 운용하는 정책금리입니다. 예금·대출·채권금리의 기준점 역할을 합니다."],
    ["금리가 오르면 어떤 일이 발생하는가?","대출 부담과 저축 유인이 커져 소비·투자가 둔화될 수 있고, 수요 압력이 줄어 물가 안정에 도움이 될 수 있습니다."],
    ["금리가 내리면 어떤 일이 발생하는가?","자금 조달 비용이 낮아져 소비·투자를 지원하지만, 환율·부채·자산가격 위험을 키울 수도 있습니다."],
    ["CPI란?","소비자물가지수로 가계가 구입하는 상품과 서비스 가격의 변화를 측정합니다. 금리 판단에서 물가 압력을 보는 핵심 지표입니다."],
    ["GDP란?","일정 기간 생산된 최종 재화와 서비스의 가치입니다. 성장 둔화는 완화 필요성을, 과열은 긴축 필요성을 높일 수 있습니다."],
    ["실업률이 금리에 미치는 영향","실업률 상승은 경기 약화 신호가 될 수 있어 인하 압력을 높이지만, 물가와 금융안정 상황을 함께 봐야 합니다."],
    ["환율이 금리에 미치는 영향","원화 약세는 수입물가와 자금 유출 부담을 높여 금리 인하를 제약할 수 있습니다."],
    ["미국 CPI가 한국 금리에 영향을 주는 과정","미국 물가 → 연준 정책금리 기대 → 달러와 글로벌 자금 흐름 → 원·달러 환율과 한미 금리 차 → 한국 정책 여건으로 연결됩니다."],
    ["한미 기준금리 차의 의미","한국 금리에서 미국 금리를 뺀 값입니다. 격차 자체보다 환율, 자본 흐름과 각국 경기 상황을 함께 해석해야 합니다."],
  ];
  const calculations = [
    ["CPI 전년 동월 대비 계산","(현재 CPI ÷ 12개월 전 CPI − 1) × 100","현재 120, 전년 116이면 (120÷116−1)×100 = 3.45%"],
    ["CPI 전월 대비 계산","(현재 CPI ÷ 전월 CPI − 1) × 100","현재 120, 전월 119.5이면 0.42%"],
    ["환율 변화율 계산","(현재 환율 ÷ 과거 환율 − 1) × 100","1,450원에서 1,500원이면 3.45% 상승"],
    ["한미 기준금리 차 계산","한국 기준금리 − 미국 기준금리","한국 3.50%, 미국 5.25%이면 −1.75%p"],
    ["금리 변화량 계산","현재 기준금리 − 과거 기준금리","3.50%에서 3.25%가 되면 −0.25%p"],
    ["1개월·3개월·6개월 변화 변수 계산","현재 값 − 각 시차의 과거 값","현재 물가 3.0%, 3개월 전 3.6%이면 3개월 변화는 −0.6%p"],
  ];
  const ml = (group,title,definition,level,status,principle,why,application,pros,limits,related,example,visual="") => ({group,title,definition,level,status,principle,why,application,pros,limits,related,example,visual});
  const dataStates = {
    available:{label:"데이터 있음",message:"유효한 계산 데이터로 결과를 표시합니다."},
    notApplied:{label:"현재 미적용",message:"충분한 예측 표본이 확보된 후 Calibration Curve와 Brier Score를 이용해 확률 보정 성능을 평가할 예정입니다."},
    insufficient:{label:"데이터 부족",message:"유효한 표본이 충분하지 않아 결과를 계산하지 않습니다."},
    error:{label:"계산 오류",message:"계산 결과를 확인할 수 없습니다. 데이터 상태를 점검해주세요."},
  };
  const dataState = (state) => { const value=dataStates[state] ?? dataStates.error; return `<section class="ml-data-state ${state}" data-state="${state}" role="status"><div><strong>확률 보정 상태</strong><span>${value.label}</span></div><p>${value.message}</p></section>`; };
  const machine = [
    ml("모델 기초","지도학습","입력 데이터와 정답을 함께 학습해 새로운 입력의 결과를 예측하는 방식","기초","현재 적용","과거 경제지표를 X, 3개월 뒤 실제 금리 방향을 y로 두고 X와 y의 관계를 학습합니다.","경제 상황과 실제 정책 결정이 함께 기록되어 있어 분류 문제로 학습할 수 있습니다.","월별 CPI·환율·실업률·국고채·미국 금리와 시차 변수를 입력하고 인하·동결·인상을 정답으로 사용합니다.","평가 기준이 명확하고 새 관측치의 결과를 자동 계산할 수 있습니다.","학습에 없던 정책 환경이나 돌발 충격에는 약하며, 관측된 관계가 인과관계를 뜻하지 않습니다.","분류 · 정답 레이블 · 훈련/검증 분리","경제지표 → 모델 학습 ← 실제 3개월 뒤 결정",'<div class="ml-flow"><b>경제지표 X</b><i>+</i><b>실제 결정 y</b><i>→</i><strong>학습 모델</strong></div>'),
    ml("모델 기초","분류 문제","입력을 미리 정한 범주 중 하나로 구분하는 문제","기초","현재 적용","모델은 세 클래스의 점수를 계산하고 가장 큰 값을 인하·동결·인상 중 최종 방향으로 선택합니다.","정책금리는 단계적으로 조정되므로 정확한 수치보다 다음 방향이 실무적으로 해석하기 쉽습니다.","현재 금리와 3개월 뒤 금리를 비교해 낮으면 인하, 같으면 동결, 높으면 인상으로 레이블을 만듭니다.","정책 방향과 클래스별 불확실성을 함께 제시할 수 있습니다.","방향을 맞혀도 0.25%p인지 0.50%p인지 변화 폭은 설명하지 못합니다.","다중 분류 · 예측 확률 · 회귀","현재 2.50% → 3개월 뒤 2.75%=인상, 2.50%=동결, 2.25%=인하",'<div class="ml-classes"><span>인하</span><span>동결</span><span>인상</span></div>'),
    ml("모델 기초","Random Forest","여러 의사결정나무를 독립적으로 학습하고 결과를 종합하는 앙상블 모델","기초","현재 모델에 사용","각 나무는 표본과 변수 일부를 무작위로 보고 질문을 반복합니다. 모든 나무의 클래스 확률을 평균해 결과를 만듭니다.","경제 변수의 비선형 관계와 상호작용을 별도 수식 없이 학습하고 단일 나무의 과적합을 줄일 수 있습니다.","300개 트리, 깊이 후보 2·4·제한 없음, 최소 잎 2·4, 변수 후보 sqrt·70%, 클래스 가중치 후보 없음·balanced를 탐색합니다. 현재 선택값은 깊이 2, 최소 잎 2, sqrt, balanced입니다.","전처리 부담이 작고 비선형성·상호작용·변수 중요도를 다룰 수 있습니다.","시간 순서를 스스로 이해하지 않으며 개별 판단 방향은 Feature Importance만으로 설명할 수 없습니다. 불균형 데이터에서는 다수 클래스 편향도 점검해야 합니다.","의사결정나무 · Bagging · Feature Importance","각기 다른 경제지표를 본 3개 트리가 인상·동결·인상을 선택하면 투표 결과는 인상입니다.",'<div class="tree-vote"><span>Tree 1<br><b>인상</b></span><span>Tree 2<br><b>동결</b></span><span>Tree 3<br><b>인상</b></span><i>→</i><strong>인상</strong></div>'),
    ml("모델 기초","XGBoost","앞선 트리의 오류를 다음 작은 트리가 순차적으로 보완하는 부스팅 모델","중급","현재 모델에 사용","첫 트리의 오차를 계산하고 다음 트리가 그 오차를 줄이는 과정을 반복한 뒤 모든 트리의 점수를 합산합니다.","작은 표 형식 데이터의 복잡한 비선형 관계를 세밀하게 학습하고 Random Forest와 다른 편향을 비교할 수 있습니다.","200개 트리, subsample 0.8, colsample 0.8, L2 규제 2.0을 고정합니다. 깊이 1~3, 학습률 0.03·0.08, min_child_weight 2·5, 균형 가중치 여부를 탐색하며 현재 선택값은 깊이 1, 학습률 0.03, 최소 자식 가중치 2, 균형 가중치 미사용입니다.","예측력이 높을 수 있고 규제와 샘플링으로 복잡도를 조절할 수 있습니다.","설정에 민감하고 표본이 작으면 과적합되거나 확률이 불안정할 수 있습니다.","Boosting · 학습률 · 규제 · 잔차","기본 예측 → 오류 확인 → 보완 트리 → 오류 감소 → 최종 합산",'<div class="boost-flow"><b>Tree 1</b><i>오류</i><b>Tree 2</b><i>보완</i><b>Tree 3</b><i>→</i><strong>최종 점수</strong></div>'),
    ml("모델 기초","두 모델의 앙상블","서로 다른 모델의 판단을 결합해 최종 결과를 만드는 방식","중급","현재 적용","RateScope의 메인 전망은 Random Forest와 XGBoost의 인하·동결·인상 확률을 클래스별로 1:1 단순 평균하고 가장 큰 평균 확률을 선택합니다.","독립 트리 평균에 강한 Random Forest와 오류 보완에 강한 XGBoost의 학습 차이를 활용합니다.","각 모델의 개별 예측과 확률을 먼저 보존한 뒤 (RF 확률+XGB 확률)÷2를 계산합니다. 가중 평균이나 다수결은 사용하지 않습니다. 의견 불일치는 별도 강제 규칙 없이 평균 확률에 반영되며 불확실성 신호로 해석합니다.","한 모델의 편향을 완화하고 모델 합의 여부를 확인할 수 있습니다.","두 모델이 같은 데이터와 트리 구조를 사용해 오류가 완전히 독립적이지 않으며, 평균이 항상 더 정확한 것은 아닙니다.","확률 평균 · 모델 다양성 · 불확실성","RF: 인하 20·동결 50·인상 30%, XGB: 10·40·50% → 평균 15·45·40% → 동결",'<div class="ensemble-flow"><span>Random Forest<br><b>클래스별 확률</b></span><span>XGBoost<br><b>클래스별 확률</b></span><i>÷ 2</i><strong>최대 평균 확률</strong></div>'),
    ml("모델 기초","2단계 분류","변경 여부와 변경 방향을 두 개의 이진 판단으로 나누는 방식","중급","Reliability Lab 실험","1단계 P(변경), 2단계 P(인하|변경)를 계산합니다. 최종값은 인하=P(변경)×P(인하|변경), 동결=1−P(변경), 인상=P(변경)×[1−P(인하|변경)]입니다.","동결이 많은 데이터에서 한 번에 세 클래스를 구분할 때 생기는 다수 클래스 편향을 분석하기 위해서입니다.","2008년 이후 동일 19개 변수를 쓰는 Logistic Regression 실험입니다. 1단계 Gap은 3개월, 변경 사례만 학습하는 2단계 내부 Gap은 1개월입니다. 메인 RF·XGBoost 앙상블과는 별도 실험입니다.","각 단계 목적과 오류 위치가 명확하고 희소한 변경 방향을 별도로 학습합니다.","1단계 오류가 최종 결과로 전파되고 조건부 확률 결합이 복잡합니다. 단일 3-class보다 항상 우수하지 않습니다.","계층 분류 · 조건부 확률 · 클래스 불균형","경제지표 → 변경/동결 → 변경이면 인하/인상 → 세 클래스 확률",'<div class="hierarchy-flow"><b>경제지표</b><i>→</i><strong>변경 여부</strong><span>동결</span><span>변경 → 인하 / 인상</span></div>'),
    ml("데이터와 검증","클래스 불균형","일부 정답 클래스가 다른 클래스보다 훨씬 많은 상태","기초","현재 대응","항상 다수 클래스만 예측해도 Accuracy가 높아질 수 있으므로 클래스별 Recall과 Macro F1을 함께 봅니다.","금리 결정은 변경보다 동결이 자주 나타나 희소한 인하·인상을 놓치기 쉽습니다.","현재 포스트 팬데믹 학습 51건은 동결 29·인상 12·인하 10건입니다. RF는 balanced 클래스 가중치 후보, XGBoost는 균형 샘플 가중치 후보를 탐색하고 Macro F1으로 선택합니다. Reliability Lab에서는 계층 분류와 class_weight 후보를 사용합니다. 오버·언더샘플링은 적용하지 않습니다.","희소 클래스 탐지 문제를 드러내고 대응 방법을 비교할 수 있습니다.","가중치 적용이 반드시 성능을 높이지 않으며 검증 구간에 클래스가 아예 없을 수 있습니다.","Accuracy · Recall · Macro F1 · 가중치","동결만 예측하면 29/51은 맞지만 인하·인상 Recall은 0이 됩니다.",'<div class="imbalance-bars"><span><i style="width:57%"></i><b>동결 29</b></span><span><i style="width:24%"></i><b>인상 12</b></span><span><i style="width:20%"></i><b>인하 10</b></span></div>'),
    ml("데이터와 검증","TimeSeriesSplit","과거로 학습하고 그 이후 시점으로 검증하는 시간 순서 분할","중급","현재 적용","학습 창은 점차 늘어나고 검증 창은 미래에 고정됩니다. 무작위로 과거와 미래를 섞지 않습니다.","실제 서비스에서 미래 데이터로 과거를 예측할 수 없으므로 현실적인 성능 평가와 누출 방지가 필요합니다.","메인 튜닝은 2022-01 이후 자료에서 4개 expanding split, 각 검증 6개월, Gap 3개월입니다. 후보 설정 선택과 표시 성능에 같은 fold를 쓰므로 결과가 낙관적일 수 있다는 경고도 제공합니다.","시간 순서를 지키며 구간별 성능 변화를 확인할 수 있습니다.","표본이 줄고 특정 fold에 일부 클래스가 없을 수 있으며 구조 변화에 따라 성능 편차가 큽니다.","Expanding window · Gap · Walk-forward","[과거 학습] [3개월 Gap] [미래 6개월 검증]을 네 번 확장합니다.",'<div class="split-visual"><span class="train">학습</span><span class="gap">Gap</span><span class="test">검증</span><span class="train wide">확장 학습</span><span class="gap">Gap</span><span class="test">검증</span></div>'),
    ml("데이터와 검증","Gap","학습 종료와 검증 시작 사이에 비워두는 기간","중급","현재 적용","예측 목표 기간과 검증 입력이 겹치지 않도록 일정 개월을 분할에서 제외합니다.","3개월 뒤 금리를 정답으로 만들었기 때문에 인접 샘플의 목표 기간 중첩과 간접 미래정보 위험을 줄여야 합니다.","메인 TimeSeriesSplit과 Reliability Lab 외부 검증의 Gap은 예측 horizon과 같은 3개월입니다. 계층 모델 2단계 내부 튜닝은 변경 사례만 사용하며 Gap 1을 사용합니다.","목표 중첩으로 인한 성능 과대평가를 줄입니다.","Gap이 클수록 학습 표본이 줄며 모든 형태의 누출을 자동으로 해결하지는 않습니다.","예측 horizon · 데이터 누출 · Purged split","학습 종료 3월 → 4~6월 제외 → 7월부터 검증",'<div class="gap-visual"><b>학습</b><i>3개월 비움</i><strong>검증</strong></div>'),
    ml("데이터와 검증","Nested Time Series Validation","설정 선택용 내부 검증과 최종 평가용 외부 검증을 분리하는 방식","중급","Reliability Lab 실험","각 외부 학습 구간 안에서 3개 TimeSeriesSplit으로 C와 class_weight를 고른 뒤, 손대지 않은 외부 미래 구간을 평가합니다.","같은 검증 결과로 설정을 고르고 성능까지 보고하면 과대평가될 수 있기 때문입니다.","2008-01 이후 219개월, 외부 5개 expanding split, 각 최종 평가 12개월, 외부 Gap 3개월입니다. 내부는 test_size 4~12개월, 3 splits이며 Log Loss로 C 0.03·0.1·0.3·1·3과 class_weight 없음·balanced를 선택합니다.","튜닝 편향을 줄이고 더 보수적인 외부 성능을 제공합니다.","계산량이 크고 각 외부 구간 표본·클래스 수가 작으면 결과 변동성이 큽니다.","내부 검증 · 외부 평가 · Log Loss","외부 학습 안에서 최적 설정 선택 → 한 번도 쓰지 않은 다음 12개월 평가",'<div class="nested-visual"><section><b>외부 학습</b><span>내부 학습</span><span>내부 검증</span></section><i>→</i><strong>외부 12개월 평가</strong></div>'),
    ml("데이터와 검증","Walk-forward Validation","시점마다 과거 데이터를 갱신해 다음 미래를 반복 예측하는 백테스트","중급","Historical Backtest에 적용","학습 → 다음 시점 예측 → 실제값 확인 → 데이터 추가 과정을 시간 순서대로 반복합니다.","실제 운영에서 새 지표가 들어올 때 모델을 갱신하는 흐름을 과거에서 재현할 수 있습니다.","별도 post_pandemic_forecast 실험에 expanding-window walk-forward와 3개월 target gap이 구현되어 있습니다. 현재 Prediction History의 저장된 Live Prediction과 동일한 기록은 아니며 반드시 Historical Backtest로 구분합니다.","시간별 성능과 국면 변화에 따른 약점을 확인할 수 있습니다.","현재 사용할 수 없었던 수정치나 데이터가 섞이면 당시 실시간 재현과 달라질 수 있습니다.","백테스트 · 빈티지 데이터 · 모델 재학습","2019까지 학습→2020 예측→결과 추가→2021 예측",'<div class="walk-visual"><b>학습</b><i>→</i><strong>다음 시점 예측</strong><i>→</i><span>결과 추가·반복</span></div>'),
    ml("데이터와 검증","데이터 누출","예측 당시 알 수 없던 미래 정보가 학습이나 검증에 들어가는 문제","중급","부분 대응","시간 순서 분할, 목표 horizon만큼의 Gap, 과거 시차 변수만 사용해 미래 정보 혼입을 줄입니다.","누출이 있으면 실제 운영에서는 얻을 수 없는 비현실적으로 높은 성능이 나타납니다.","1·3·6개월 과거 변화량만 만들고 3개월 미래 목표를 사용합니다. TimeSeriesSplit과 Gap을 적용하며 최신 입력 기준일도 저장합니다. 다만 월별 수정 통계의 실시간 빈티지를 완전히 구분하지 않아 Reliability Lab 경고에 명시합니다.","평가를 실제 예측 조건에 가깝게 만듭니다.","분할만으로 통계 수정치·발표 시차·뉴스 시점 문제를 모두 해결할 수 없습니다.","Gap · 빈티지 데이터 · 발표 시차","전체 기간으로 전처리한 뒤 분할하거나 미래 결정 뒤 뉴스를 쓰면 누출입니다.",'<div class="leak-visual"><b>과거 정보</b><i class="blocked">× 미래 정보 차단</i><strong>검증</strong></div>'),
    ml("모델 해석","Feature Importance","모델 전체에서 변수가 예측 규칙에 사용된 상대적 정도","기초","현재 적용","트리 분할이 오류를 얼마나 줄였는지를 누적해 변수별 비중을 계산합니다.","복잡한 모델이 어떤 지표를 주로 참고했는지 전체적인 점검 단서를 제공하기 위해서입니다.","RF와 XGBoost별 상위 8개 변수를 저장하고 모델 페이지 막대그래프에 변수명·중요도·경제적 의미를 표시합니다. 최근 값은 Home 판단 근거와 지표 영역에서 연결합니다.","전체 모델의 관심 변수를 빠르게 비교할 수 있습니다.","중요도가 높아도 인과관계가 아니며, 특정 예측에서 인상 또는 인하 어느 방향으로 작용했는지도 알 수 없습니다. 상관된 변수끼리 중요도가 나뉠 수 있습니다.","SHAP · 상관관계/인과관계 · 변수 상호작용","한미 금리 차 중요도 0.15는 전체 분할 기여 비중이지 ‘인상 원인 15%’가 아닙니다.",'<div class="importance-visual"><span><b style="width:88%"></b>한미 금리 차</span><span><b style="width:70%"></b>채권-정책금리 차</span><span><b style="width:58%"></b>물가</span></div>'),
    ml("모델 해석","SHAP","개별 예측에서 각 변수가 모델 출력을 어느 방향으로 얼마나 움직였는지 배분하는 설명법","중급","향후 개선","기준 예측에서 출발해 각 변수의 기여값을 더해 특정 클래스의 최종 모델 출력에 도달합니다.","현재 한 시점의 인상·동결·인하 판단에 어떤 변수가 어떤 방향으로 작용했는지 설명하기 위해 필요합니다.","현재 SHAP 계산이나 저장 기능은 없습니다. UI의 Feature Importance를 SHAP처럼 표현하지 않으며 향후 모델별·클래스별 SHAP을 추가할 계획입니다.","개별 예측과 방향성을 설명할 수 있습니다.","모델 행동을 설명할 뿐 경제적 인과를 증명하지 않으며 배경 데이터 선택에 민감합니다.","Feature Importance · 국소 설명 · 인과관계","향후 예: 환율 +0.08(인상 쪽), 성장 둔화 −0.05(인하 쪽). 현재 실제 수치가 아닙니다.",'<div class="shap-visual"><span>인하 방향</span><i></i><b>기준</b><i></i><span>인상 방향</span></div>'),
    ml("모델 해석","예측 확률","모델이 각 클래스를 상대적으로 얼마나 강하게 선택했는지 나타내는 출력","기초","현재 적용","각 모델의 predict_proba 결과를 세 클래스 순서로 맞추고, 메인 전망에서는 RF와 XGBoost 확률을 동일 가중 평균합니다.","하나의 방향만 보여주는 것보다 대안 클래스와 모델 간 의견 차이를 함께 보여주기 위해서입니다.","클래스별 확률·최종 최대 클래스·두 모델 개별 확률을 표시합니다. 표본이 작고 보정되지 않았다는 경고를 함께 제공합니다.","판단 강도와 경쟁 클래스 간 간격을 볼 수 있습니다.","70% 출력이 현실에서 정확히 70% 발생한다는 뜻은 아닙니다. 모델 점수이며 데이터 품질·검증 성능과 함께 봐야 합니다.","확률 보정 · 신뢰도 · Entropy","인하 15·동결 70·인상 15%이면 동결을 선택하지만 ‘실제 70%’로 단정하지 않습니다.",'<div class="prob-visual"><span style="--p:15%">인하 15%</span><span style="--p:70%">동결 70%</span><span style="--p:15%">인상 15%</span></div>'),
    ml("모델 해석","확률 보정","예측 확률과 실제 발생 빈도가 비슷해지도록 조정하는 과정","중급","향후 개선","별도 검증 데이터에서 모델 확률과 실제 빈도의 관계를 학습해 Platt Scaling 또는 Isotonic Regression으로 보정합니다.","분류를 잘 맞히는 모델도 지나치게 자신만만하거나 보수적일 수 있기 때문입니다.","현재 메인 모델은 미보정 확률입니다. Reliability Lab은 Brier Score를 평가하지만 별도 calibration 모델은 적용하지 않습니다. 충분한 표본 확보 후 Calibration Curve와 Brier Score를 함께 검증할 계획입니다.","확률을 의사결정 임계값과 위험관리에서 더 일관되게 사용할 수 있습니다.","보정용 데이터가 추가로 필요하고 작은 표본에서는 Isotonic이 과적합될 수 있습니다.","Platt Scaling · Isotonic · Brier Score · Calibration Curve","70% 예측 100건 중 약 70건이 실제 발생하면 잘 보정된 상태입니다.",dataState("notApplied")),
    ml("모델 평가","Accuracy","전체 예측 중 정답을 맞힌 비율","기초","현재 평가","정답 건수를 전체 평가 건수로 나눕니다.","가장 직관적인 전체 성능 지표이지만 불균형 데이터에서는 단독 사용이 위험합니다.","모델·fold별 Accuracy를 저장하고 항상 동결을 예측하는 baseline과 함께 비교합니다.","이해하고 모델 간 비교하기 쉽습니다.","동결 70% 데이터에서 항상 동결만 말해도 70%가 되므로 희소 클래스 성능을 숨깁니다.","Macro F1 · 클래스 불균형 · Baseline","10건 중 6건 정답이면 Accuracy 60%입니다.",'<div class="accuracy-visual"><b>정답 6</b><span>오답 4</span><strong>60%</strong></div>'),
    ml("모델 평가","Precision·Recall·F1-score","특정 클래스를 예측한 정확성, 실제 클래스를 찾아낸 비율, 두 지표의 균형","중급","부분 적용","Precision=TP/(TP+FP), Recall=TP/(TP+FN), F1은 Precision과 Recall의 조화평균입니다. Macro F1은 세 클래스 F1을 같은 비중으로 평균합니다.","동결이 많은 상황에서도 인하·인상을 실제로 탐지하는지 확인하기 위해서입니다.","메인 튜닝은 클래스별 Recall과 Macro F1을 계산하고 Macro F1 우선, Accuracy 차순으로 최적 설정을 고릅니다. Precision 개별값은 현재 출력에 저장하지 않아 향후 상세 평가표에서 추가합니다.","희소 클래스의 놓침과 오경보를 구분할 수 있습니다.","클래스 표본이 매우 적으면 값이 크게 흔들리고 Precision과 Recall 사이에 trade-off가 있습니다.","Confusion Matrix · 임계값 · Macro/Micro 평균","인상 5건을 예측해 3건이 맞으면 Precision 60%; 실제 인상 6건 중 3건을 찾으면 Recall 50%입니다.",'<div class="metric-trio"><span><b>Precision</b>예측의 정확성</span><span><b>Recall</b>실제 탐지율</span><span><b>F1</b>두 값의 균형</span></div>'),
    ml("모델 평가","Confusion Matrix","실제 클래스와 예측 클래스를 교차해 오류 유형을 보여주는 표","기초","향후 UI 개선","행을 실제, 열을 예측으로 두고 각 칸의 건수 또는 행 기준 비율을 기록합니다.","Accuracy만으로 볼 수 없는 ‘실제 인하를 동결로 놓치는 오류’ 같은 패턴을 찾기 위해서입니다.","현재 백엔드는 fold 예측의 요약 지표를 저장하지만 3×3 행렬 값은 결과 JSON에 저장하지 않습니다. 다음 개선에서 fold별 실제·예측을 저장해 실제 행렬로 연결합니다. 아래 도식은 구조 예시이며 성능 수치가 아닙니다.","어떤 클래스를 무엇으로 혼동하는지 직관적으로 확인합니다.","건수와 비율을 함께 보지 않으면 불균형을 오해할 수 있습니다.","Precision · Recall · 오분류 비용","대각선은 정답, 대각선 밖은 인하→동결 같은 오분류입니다.",'<div class="matrix-visual"><i></i><b>예측 인하</b><b>예측 동결</b><b>예측 인상</b><strong>실제 인하</strong><span class="hit">정답</span><span>오류</span><span>오류</span><strong>실제 동결</strong><span>오류</span><span class="hit">정답</span><span>오류</span><strong>실제 인상</strong><span>오류</span><span>오류</span><span class="hit">정답</span></div>'),
    ml("모델 위험과 운영","과적합과 과소적합","과거를 지나치게 외우거나 반대로 중요한 패턴도 배우지 못한 상태","기초","현재 대응","모델 복잡도와 규제를 조절하고 시간순 검증의 학습·검증 성능 차이를 확인합니다.","인하·인상 사례가 적어 소수 사건을 외우거나, 너무 얕은 모델이 정책 국면을 놓칠 수 있습니다.","RF 깊이·최소 잎·변수 수, XGBoost 깊이·학습률·최소 자식·L2 규제·샘플링을 제한하고 TimeSeriesSplit으로 선택합니다. Reliability Lab은 nested 외부 평가를 별도로 둡니다. 조기 종료는 현재 사용하지 않습니다.","복잡도 후보와 미래 구간 평가로 위험을 줄입니다.","현재 메인 튜닝은 선택과 성능 측정 fold가 같아 낙관 편향 가능성이 남습니다.","Bias-Variance · 규제 · Nested Validation","학습 95%, 미래 검증 40%라면 과적합 가능성을 의심합니다.",'<div class="fit-visual"><span>과소적합</span><strong>적정 복잡도</strong><span>과적합</span></div>'),
    ml("모델 위험과 운영","데이터 드리프트와 구조적 변화","입력 분포가 달라지거나 변수와 정책 결정의 관계 자체가 바뀌는 현상","중급","부분 대응","최근 입력 범위와 기간별 성능을 관찰하고 필요하면 학습 기간·가중치·모델을 갱신합니다.","환율 수준 변화는 드리프트이고, 팬데믹 뒤 물가와 금리 관계 변화는 구조 변화일 수 있습니다.","포스트 팬데믹 모델을 별도로 운영하고 Reliability Lab에서 60개월 반감기의 최근 데이터 가중치와 2008년 이후 국면을 비교합니다. 자동 드리프트 탐지 경보는 아직 없습니다.","기간별 모델 비교로 오래된 관계와 최신 관계의 차이를 볼 수 있습니다.","최근 가중치가 구조 변화를 완전히 해결하지 못하며 블랙 스완 발생 시 과거 관계가 급격히 무너질 수 있습니다.","롤링 윈도우 · 국면 탐지 · 스트레스 테스트","과거 환율 1,000~1,300원 학습 후 1,500원대 입력이 지속되면 드리프트를 점검합니다.",'<div class="drift-visual"><b>과거 분포</b><i>→ 이동 →</i><strong>현재 분포</strong></div>'),
    ml("모델 위험과 운영","모델 재학습과 버전 관리","새 데이터로 모델을 갱신하고 코드·데이터·설정·결과를 함께 추적하는 운영 절차","중급","부분 적용","정해진 업데이트 작업이 최신 경제지표를 수집하고 특징·모델·출력 파일을 다시 생성합니다. Git 커밋과 결과 기준일로 변경을 추적합니다.","정책과 데이터가 계속 바뀌므로 오래된 모델을 그대로 두면 성능과 설명의 신뢰가 낮아집니다.","GitHub Actions가 데이터를 갱신하고 forecast JSON에 학습기간·입력 기준일·선택 파라미터를 저장합니다. 다만 전용 모델 레지스트리, 승인·롤백, 드리프트 기반 자동 재학습 기준은 아직 없습니다.","재현성과 변경 이력 확인이 쉬워집니다.","데이터 수정치·라이브러리 버전·환경까지 고정하지 않으면 같은 코드도 결과가 달라질 수 있습니다.","MLOps · 데이터 버전 · 모델 레지스트리 · 모니터링","v1: 2022~2025 학습 → v2: 2022~2026 학습처럼 기준일과 성능을 함께 기록합니다.",'<div class="version-visual"><span>데이터 기준일</span><i>+</i><span>코드 커밋</span><i>+</i><span>파라미터</span><strong>→ 모델 버전</strong></div>'),
  ];
  const risks = [
    ["블랙 스완","과거에 거의 없던 극단적 충격","예상 밖의 거대한 파도","팬데믹·전쟁·금융 시스템 붕괴","유사 학습 사례가 부족하고 변수 관계가 급변합니다.","현재 모델은 발생 자체를 예측하지 못하며 불확실성 경고만 제공합니다.","스트레스 테스트, 이상 탐지와 전문가 규칙을 결합합니다."],
    ["그레이 라이노","알려져 있지만 대응이 늦을 수 있는 큰 위험","멀리서 보이지만 피하지 않는 위험","가계부채·부동산 과열·인구구조 변화","발생 시점과 임계 수준이 불확실합니다.","관련 지표가 현재 Feature에 모두 포함된 것은 아닙니다.","부채·주택·연체율을 시차 Feature로 추가합니다."],
    ["구조적 변화","경제 변수 사이의 관계가 장기적으로 바뀌는 현상","과거의 지도와 현재 길이 달라지는 상황","팬데믹 이후 물가·공급망 변화","과거에 맞던 규칙이 현재에는 틀릴 수 있습니다.","포스트 팬데믹 모델을 별도로 비교합니다.","국면 탐지와 기간별 모델을 운영합니다."],
    ["데이터 드리프트","모델 입력 분포가 학습 당시와 달라지는 현상","익숙하지 않은 범위의 숫자가 들어오는 상황","환율·물가의 장기 레벨 변화","학습 범위 밖에서는 외삽이 불안정합니다.","주요 지표의 과거 범위 이탈을 점검합니다.","드리프트 알림과 재학습 기준을 둡니다."],
    ["스트레스 테스트","극단적 가정을 넣어 모델과 시스템의 반응을 확인하는 방법","사고가 나기 전 비상훈련","환율 20% 상승·물가 재급등 시나리오","시나리오가 실제 미래와 같다는 보장은 없습니다.","현재 정규 예측 파이프라인에는 미포함입니다.","정책 변수별 충격 시나리오를 별도 제공합니다."],
    ["극단적 시나리오 분석","여러 위험이 동시에 발생하는 꼬리 위험을 비교하는 분석","최악·중간·기본 경로를 나란히 보는 방법","전쟁과 공급 충격, 환율 급등의 결합","변수 간 충격 관계를 가정해야 합니다.","현재 단일 최신 입력을 사용합니다.","확률적 시나리오와 민감도 분석을 추가합니다."],
  ];
  const machineItems = machine.map((item) => ({
    title:item.title,
    definition:item.definition ?? "",
    group:item.group,
    meta:[item.level,item.status].filter(Boolean).join(" · "),
    searchable:Object.values(item).join(" "),
    html:`${item.visual ?? ""}${item.definition ? `<div class="ml-definition"><strong>한 줄 정의</strong><p>${item.definition}</p></div>` : ""}<dl class="ml-concept-detail">${[["쉬운 설명과 핵심 원리",item.principle],["왜 이 프로젝트에서 다루는가",item.why],["RateScope 적용",item.application],["장점",item.pros],["한계와 주의점",item.limits],["관련 개념",item.related],["간단한 예시",item.example]].filter(([,value])=>value).map(([label,value])=>`<div><dt>${label}</dt><dd>${value}</dd></div>`).join("")}</dl><a href="/model#model-classroom">실제 모델과 검증 결과 보기 →</a>`,
  }));
  const categories = [
    {id:"basic",name:"경제 기초",items:basic.map(([title,body])=>({title,html:`<p>${body}</p><a href="/#current-prediction">현재 전망과 연결해서 보기 →</a>`}))},
    {id:"calculation",name:"경제지표 계산법",items:calculations.map(([title,formula,example])=>({title,html:`<dl class="formula-detail"><div><dt>공식</dt><dd><code>${formula}</code></dd></div><div><dt>숫자 예시</dt><dd>${example}</dd></div></dl><a href="/model#features">관련 변수 보기 →</a>`}))},
    {id:"machine",name:"머신러닝 이해",items:machineItems},
    {id:"risk",name:"경제 리스크",items:risks.map(([title,definition,easy,example,difficulty,current,future])=>({title,html:`<dl class="risk-learning"><div><dt>정의</dt><dd>${definition}</dd></div><div><dt>쉬운 설명</dt><dd>${easy}</dd></div><div><dt>대표 사례</dt><dd>${example}</dd></div><div><dt>AI가 다루기 어려운 이유</dt><dd>${difficulty}</dd></div><div><dt>현재 모델 반영</dt><dd>${current}</dd></div><div><dt>향후 개선</dt><dd>${future}</dd></div></dl><a href="/insight">프로젝트 인사이트 보기 →</a>`}))},
  ];
  let selected="all";
  const linkedTopic=new URLSearchParams(location.search).get("topic") ?? "";
  if(linkedTopic)document.querySelector("#learn-search").value=linkedTopic;
  function render(){const query=document.querySelector("#learn-search").value.trim().toLowerCase();let count=0;document.querySelector("#learn-content").innerHTML=categories.filter(c=>selected==="all"||c.id===selected).map(category=>{const items=category.items.filter(item=>(item.searchable||item.title+item.html).toLowerCase().includes(query));count+=items.length;if(!items.length)return"";let lastGroup="";const content=items.map(item=>{const group=item.group&&item.group!==lastGroup?`<h3 class="learn-subgroup">${item.group}</h3>`:"";if(item.group)lastGroup=item.group;const supporting=[item.definition,item.meta].filter(Boolean);return `${group}<details><summary aria-expanded="false"><span class="learn-summary-copy"><b>${item.title ?? ""}</b>${supporting.length?`<small>${item.definition ? `<span>${item.definition}</span>` : ""}${item.meta ? `<em>${item.meta}</em>` : ""}</small>`:""}</span><span class="learn-chevron" aria-hidden="true"></span></summary><div>${item.html ?? ""}</div></details>`;}).join("");return `<section class="learn-category"><header><span>${category.name}</span><strong>${items.length}개 주제</strong></header>${content}</section>`;}).join("");document.querySelector("#learn-result-count").textContent=`${count}개의 학습 주제`;document.querySelectorAll("#learn-content details").forEach((detail)=>detail.addEventListener("toggle",()=>detail.querySelector("summary")?.setAttribute("aria-expanded",String(detail.open))));}
  document.querySelector("#learn-filters").innerHTML=[{id:"all",name:"전체"},...categories].map(c=>`<button type="button" data-category="${c.id}" class="${c.id==="all"?"active":""}">${c.name}</button>`).join("");
  document.querySelector("#learn-filters").addEventListener("click",e=>{const b=e.target.closest("[data-category]");if(!b)return;selected=b.dataset.category;document.querySelectorAll("[data-category]").forEach(x=>x.classList.toggle("active",x===b));render();});document.querySelector("#learn-search").addEventListener("input",render);render();if(linkedTopic){const detail=document.querySelector("#learn-content details");if(detail){detail.open=true;detail.querySelector("summary")?.setAttribute("aria-expanded","true");}}
})();
